app:
  host: https://gitlab.com/
  token: sLMKNvyzMfhke9yyBGEk


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/skb-lab
    username: root
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect

