spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/..
    username: root
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect

app:
  host: www.gitlab.com //для вида
  token: aaaaaa
