app:
  host: https://gitlab.com
  token: S5KXrL3nxkAoeDbVr2XB
  project_id: 27919912


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/skb-lab
    username: root
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect

